// RootLayoutServer.js (Server-side component)
export const metadata = {
  title: "LMS Lottery | CRM",
  description: "Generated by create next app",
};

// Keep the rest of the code here in the client component
